server.port=${PORT:8080}

spring.application.name=jobportal

spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:23608/railway
spring.datasource.username=root
spring.datasource.password=fIWQaoWRcFMwzaPCPUNqbVlntViLNRqX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name=dyucgevvq
cloudinary.api_key=983964335226331
cloudinary.api_secret=9m1DUzGJtMU0BnUVwjim2mTrphU

jwt.secret=MySuperSecretKeyForJwtSigningMustBeLongEnough12345
jwt.expiration=86400000

# Stripe Configuration
stripe.secretKey=${STRIPE_API_KEY}
stripe.publishableKey=pk_test_51SPLNiQWlUGrlx1XM4aLdo5JxpHmP9EBmsUKm7SrqNGzIYUWsBZcoTWpuUedJAHoKdcK6mZZwn8yW7z6FipyLMHV00geGkkKWi

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rubeen.adhikari2017@gmail.com
spring.mail.password=qarz uvwe zjnh zcbk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.example.jobportal=DEBUG
logging.level.com.example.jobportal.controller.AuthController=DEBUG
logging.level.com.example.jobportal.controller.ChatController=DEBUG
logging.level.com.example.jobportal.service.impl.UserServiceImpl=DEBUG
logging.level.com.example.jobportal.service.impl.ChatServiceImpl=DEBUG
logging.level.com.example.jobportal.config.WebSocketConfig=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
